name: Template - Collect Results

on:
  workflow_call:
    inputs:
      exp-name:
        required: false
        type: string
        default: ''

jobs:
  collect-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -q matplotlib

      - name: Download JSON artifacts
        uses: actions/download-artifact@v6
        with:
          path: results/
          pattern: ${{ inputs.exp-name && format('{0}_*', inputs.exp-name) || '*' }}

      - name: Print summary
        run: python3 utils/summarize.py results/ >> $GITHUB_STEP_SUMMARY

      - name: Aggregate results
        run: python3 utils/collect_results.py results/ ${{ inputs.exp-name || 'all' }}

      - name: Upload aggregated results
        uses: actions/upload-artifact@v5
        with:
          name: results_${{ inputs.exp-name || 'all' }}
          path: agg_${{ inputs.exp-name || 'all' }}.json

      - name: Plot performance
        run: python3 utils/plot_perf.py results/ ${{ inputs.exp-name || 'all' }}
      - name: Upload performance graphs
        uses: actions/upload-artifact@v5
        with:
          name: graphs_${{ inputs.exp-name || 'all' }}
          path: |
            tput_vs_intvty_*_${{ inputs.exp-name || 'all' }}.png
            tput_vs_e2el_*_${{ inputs.exp-name || 'all' }}.png
