name: Template - Full Sweep

on:
  workflow_call:
    inputs:
      run_1k1k:
        type: boolean
        required: true
      run_8k1k:
        type: boolean
        required: true
      run_1k8k:
        type: boolean
        required: true

      use_h100:
        type: boolean
        required: true
      use_h200:
        type: boolean
        required: true
      use_b200:
        type: boolean
        required: true
      use_mi300x:
        type: boolean
        required: true
      use_mi325x:
        type: boolean
        required: true
      use_mi355x:
        type: boolean
        required: true
      use_gb200:
        type: boolean
        required: false
        default: false

jobs:
  dsr1-1k1k:
    if: ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}
      use_gb200: ${{ inputs.use_gb200 }}

  collect-dsr1-1k1k-results:
    needs: dsr1-1k1k
    if: ${{ inputs.run_1k1k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k1k'

  gptoss-1k1k:
    if: ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/gptoss-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-1k1k-results:
    needs: gptoss-1k1k
    if: ${{ inputs.run_1k1k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k1k'

  dsr1-8k1k:
    if: ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}
      use_gb200: ${{ inputs.use_gb200 }}

  collect-dsr1-8k1k-results:
    needs: dsr1-8k1k
    if: ${{ inputs.run_8k1k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_8k1k'

  gptoss-8k1k:
    if: ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/gptoss-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-8k1k-results:
    needs: gptoss-8k1k
    if: ${{ inputs.run_8k1k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_8k1k'

  dsr1-1k8k:
    if: ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}
      use_gb200: ${{ inputs.use_gb200 }}

  collect-dsr1-1k8k-results:
    needs: dsr1-1k8k
    if: ${{ inputs.run_1k8k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k8k'

  gptoss-1k8k:
    if: ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/gptoss-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-1k8k-results:
    needs: gptoss-1k8k
    if: ${{ inputs.run_1k8k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k8k'
