name: 'Test - Runner Sweep'
run-name: '${{ github.event.inputs.runner }} Sweep - ${{ github.event.inputs.model }}'
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner Type'
        required: true
        type: choice
        options:
          - 'h100'
          - 'h200'
          - 'b200'
          - 'h200-trt'
          - 'b200-trt'
          - 'mi300x'
          - 'mi325x'
          - 'mi355x'
          - 'gb200'

      image:
        description: 'Docker Image'
        required: true
        type: choice
        options:
          - 'lmsysorg/sglang:v0.4.9.post1-cu126'
          - 'lmsysorg/sglang:v0.5.0rc1-cu128-b200'
          - 'lmsysorg/sglang:v0.5.2rc2-cu126'
          - 'lmsysorg/sglang:v0.5.3rc1-cu129-b200'
          - 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2'
          - 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post1'
          - 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2'
          - 'nvcr.io#nvidia/tensorrt-llm/release:1.2.0rc0.post1'
          - 'nvcr.io#nvidia/tensorrt-llm/release:gpt-oss-dev'
          - 'nvcr.io#nvidia/ai-dynamo/tensorrtllm-runtime:0.5.1-rc0.pre3'
          - 'rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi30x-20250915'
          - 'rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi35x-20250915'
          - 'rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250915'
          - 'rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1'
          - 'vllm/vllm-openai:v0.10.2'

      model:
        description: 'Model'
        required: true
        type: choice
        options:
          - 'amd/DeepSeek-R1-0528-MXFP4-Preview'
          - 'deepseek-ai/DeepSeek-R1-0528'
          - 'nvidia/DeepSeek-R1-0528-FP4'
          - 'nvidia/DeepSeek-R1-0528-FP4-v2'
          - 'openai/gpt-oss-120b'

      framework:
        description: 'Framework'
        required: true
        type: choice
        options:
          - 'vllm'
          - 'sglang'
          - 'trt'

      precision:
        description: 'Precision'
        required: true
        type: choice
        options:
          - 'fp8'
          - 'fp4'

      exp-name:
        description: 'Experiment Name'
        required: true
        type: choice
        options:
          - 'dsr1_test'
          - 'gptoss_test'


env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_HUB_CACHE: '/mnt/hf_hub_cache/'

jobs:
  bmk_h100:
    if: ${{ inputs.runner == 'h100' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'h100-cr_0'
          - 'h100-cr_1'
          - 'h100-cw_0'
          - 'h100-cw_1'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_h200:
    if: ${{ inputs.runner == 'h200' || inputs.runner == 'h200-trt' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'h200-cw_0'
          - 'h200-cw_1'
          - 'h200-nb_0'
          - 'h200-nb_1'
          - 'h200-nb_2'
          - 'h200-nb_3'
          - 'h200-nv_0'
          - 'h200-nv_1'
          - 'h200-nv_2'
          - 'h200-nv_3'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[4]'
      conc-list: '[64]'

  bmk_b200:
    if: ${{ inputs.runner == 'b200' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'b200-nv_0'
          - 'b200-nv_1'
          - 'b200-nvd_0'
          - 'b200-nvd_1'
          - 'b200-tg_0'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_b200-trt:
    if: ${{ inputs.runner == 'b200-trt' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'b200-nv_0'
          - 'b200-nv_1'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_mi300x:
    if: ${{ inputs.runner == 'mi300x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi300x-amd_0'
          - 'mi300x-amd_1'
          - 'mi300x-amd_2'
          - 'mi300x-amd_3'
          - 'mi300x-amd_4'
          - 'mi300x-cr_0'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_mi325x:
    if: ${{ inputs.runner == 'mi325x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi325x-amd_0'
          - 'mi325x-tw_0'
          - 'mi325x-tw_1'
          - 'mi325x-tw_2'
          - 'mi325x-tw_3'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_mi355x:
    if: ${{ inputs.runner == 'mi355x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi355x-amd_0'
          - 'mi355x-amd_1'
          - 'mi355x-amd_2'
          - 'mi355x-amd_3'

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ inputs.image }}
      model: ${{ inputs.model }}
      framework: ${{ inputs.framework }}
      precision: ${{ inputs.precision }}
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk_gb200:
    if: ${{ inputs.runner == 'gb200' && inputs.framework == 'trt' }}
    uses: ./.github/workflows/benchmark-multinode-tmpl.yml
    secrets: inherit
    with:
      runner: gb200
      image: 'nvcr.io#nvidia/ai-dynamo/tensorrtllm-runtime:0.5.1-rc0.pre3'
      model: 'deepseek-r1-fp4'
      framework: 'dynamo-trtllm'
      precision: 'fp4'
      exp-name: ${{ inputs.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      mtp-mode: 'off'

  bmk_gb200-sgl:
    if: ${{ inputs.runner == 'gb200' && inputs.framework == 'sglang' }}
    uses: ./.github/workflows/benchmark-multinode-tmpl.yml
    secrets: inherit
    with:
      runner: gb200
      image: 'nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.5.1-rc0.pre1'
      model: 'deepseek-ai/DeepSeek-R1-0528'
      framework: 'dynamo-sglang'
      precision: 'fp8'
      exp-name: ${{ inputs.exp-name }}
      isl: 8192
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      mtp-mode: 'off'

  collect-test-results:
    needs: [ bmk_h100, bmk_h200, bmk_b200, bmk_b200-trt, bmk_mi300x, bmk_mi325x, bmk_mi355x, bmk_gb200, bmk_gb200-sgl ]
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
