name: 'Test - Runner Model Sweep'
run-name: '${{ github.event.inputs.runner }} Sweep'
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner Type'
        required: true
        type: choice
        options:
          - 'h100'
          - 'h200'
          - 'h200-trt'
          - 'b200'
          - 'b200-trt'
          - 'mi300x'
          - 'mi325x'
          - 'mi355x'

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_HUB_CACHE: '/mnt/hf_hub_cache/'

jobs:
  bmk-h100:
    if: ${{ inputs.runner == 'h100' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'h100-cr_0'
          - 'h100-cr_1'
          - 'h100-cw_0'
          - 'h100-cw_1'
        config:
          - { image: 'vllm/vllm-openai:v0.10.2', model: 'openai/gpt-oss-120b', framework: 'vllm', precision: 'fp4', exp-name: 'gptoss_test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk-h200:
    if: ${{ inputs.runner == 'h200' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'h200-cw_0'
          - 'h200-cw_1'
          - 'h200-nb_0'
          - 'h200-nb_1'
          - 'h200-nb_2'
          - 'h200-nb_3'
          - 'h200-nv_0'
          - 'h200-nv_1'
          - 'h200-nv_2'
          - 'h200-nv_3'
        config:
          - { image: 'lmsysorg/sglang:v0.5.2rc2-cu126', model: 'deepseek-ai/DeepSeek-R1-0528', framework: 'sglang', precision: 'fp8', exp-name: 'dsr1_test' }
          - { image: 'vllm/vllm-openai:v0.10.2', model: 'openai/gpt-oss-120b', framework: 'vllm', precision: 'fp4', exp-name: 'gptoss_test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk-h200-trt:
    if: ${{ inputs.runner == 'h200-trt' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'h200-cw_0'
          - 'h200-cw_1'
          - 'h200-nb_0'
          - 'h200-nb_1'
          - 'h200-nb_2'
          - 'h200-nb_3'
          - 'h200-nv_0'
          - 'h200-nv_1'
          - 'h200-nv_2'
          - 'h200-nv_3'
        config:
          - { image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2', model: 'deepseek-ai/DeepSeek-R1-0528', framework: 'trt', precision: 'fp8', exp-name: 'dsr1_test' }
          - { image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2', model: 'openai/gpt-oss-120b', framework: 'trt', precision: 'fp4', exp-name: 'gptoss_test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk-b200:
    if: ${{ inputs.runner == 'b200' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'b200-nvd_0'
          - 'b200-nvd_1'
          - 'b200-nvd_2'
          - 'b200-nvd_3'
        config:
          - { image: 'lmsysorg/sglang:v0.5.3rc1-cu129-b200', model: 'deepseek-ai/DeepSeek-R1-0528', framework: 'sglang', precision: 'fp8', exp-name: 'dsr1_test' }
          - { image: 'lmsysorg/sglang:v0.5.3rc1-cu129-b200', model: 'nvidia/DeepSeek-R1-0528-FP4', framework: 'sglang', precision: 'fp4', exp-name: 'dsr1_test' }
          - { image: 'vllm/vllm-openai:v0.10.2', model: 'openai/gpt-oss-120b', framework: 'vllm', precision: 'fp4', exp-name: 'gptoss_test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[4]'

  bmk-b200-trt:
    if: ${{ inputs.runner == 'b200-trt' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'b200-nv_0'
          - 'b200-nv_1'
          - 'b200-nb_0'
          - 'b200-nb_1'
        config:
          - { image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2', model: 'deepseek-ai/DeepSeek-R1-0528', framework: 'trt', precision: 'fp8', exp-name: 'dsr1_test' }
          - { image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2', model: 'nvidia/DeepSeek-R1-0528-FP4', framework: 'trt', precision: 'fp4', exp-name: 'dsr1_test' }
          - { image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2', model: 'openai/gpt-oss-120b', framework: 'trt', precision: 'fp4', exp-name: 'gptoss_test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk-mi300x:
    if: ${{ inputs.runner == 'mi300x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi300x-amd_0'
          - 'mi300x-amd_1'
          - 'mi300x-amd_2'
          - 'mi300x-amd_3'
          - 'mi300x-amd_4'
          - 'mi300x-cr_0'
          - 'mi300x-oci_0'
        config:
          - { image: 'rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi30x-20250915', model: 'deepseek-ai/DeepSeek-R1-0528', framework: 'sglang', precision: 'fp8', exp-name: 'dsr1_test' }
          - { image: 'rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1', model: 'openai/gpt-oss-120b', framework: 'vllm', precision: 'fp4', exp-name: 'gptoss_test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk-mi325x:
    if: ${{ inputs.runner == 'mi325x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi325x-amd_0'
          - 'mi325x-tw_0'
          - 'mi325x-tw_1'
          - 'mi325x-tw_2'
          - 'mi325x-tw_3'
        config:
          - { image: 'rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi30x-20250915', model: 'deepseek-ai/DeepSeek-R1-0528', framework: 'sglang', precision: 'fp8', exp-name: 'dsr1_test' }
          - { image: 'rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1', model: 'openai/gpt-oss-120b', framework: 'vllm', precision: 'fp4', exp-name: 'gptoss_test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'

  bmk-mi355x:
    if: ${{ inputs.runner == 'mi355x' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - 'mi355x-amd_0'
          - 'mi355x-amd_1'
          - 'mi355x-amd_2'
          - 'mi355x-amd_3'
        config:
          - { image: 'rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi35x-20250915', model: 'deepseek-ai/DeepSeek-R1-0528', framework: 'sglang', precision: 'fp8', exp-name: 'dsr1_test' }
          - { image: 'rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi35x-20250915', model: 'amd/DeepSeek-R1-0528-MXFP4-Preview', framework: 'sglang', precision: 'fp4', exp-name: 'dsr1_test' }
          - { image: 'rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1', model: 'openai/gpt-oss-120b', framework: 'vllm', precision: 'fp4', exp-name: 'gptoss_test' }

    name: '${{ matrix.runner }}'
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      runner: ${{ matrix.runner }}
      image: ${{ matrix.config.image }}
      model: ${{ matrix.config.model }}
      framework: ${{ matrix.config.framework }}
      precision: ${{ matrix.config.precision }}
      exp-name: ${{ matrix.config.exp-name }}
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      tp-list: '[8]'
      conc-list: '[1]'
